/**
 * 過往作品資料：三個分類（活動作品 / 專案作品 / 其他作品），各自一串作品。
 * 顯示邏輯見 _components/WorksSection.vue 與 _components/WorkDetail.vue 的 spec。
 *
 * 每筆作品欄位：
 * - CaseName   顯示名稱（允許 br 換行，以 v-html 輸出）
 * - CaseID     識別用 ID，也是燈箱截圖檔名的一部分
 * - CaseType   圖片路徑分類（web / ad / other）
 * - CoverImg   封面圖檔名，路徑為 home/{CaseType}/{CoverImg}
 * - PhotoCount 燈箱內圖片數量
 * - webLink    連結（多個以 , 分隔；空字串表示無連結）
 * - webDesc    連結說明（多個以 , 分隔）
 */
export const datas = [
  {
    type: '活動作品',
    case: [
      {
        CaseName: '活力第一！<br>神指對決',
        CaseID: '113',
        CaseType: 'web',
        CoverImg: 'web_113.png',
        PhotoCount: '4',
        webLink: 'https://firstbank-socialevent.com/2026ileo',
        webDesc: '第一銀行 活力第一！神指對決 (手機版網站 / AI 協作作品)',
      },
      {
        CaseName: '第一銀行<br>迎財納福衝第一',
        CaseID: '94',
        CaseType: 'web',
        CoverImg: 'web_94.png',
        PhotoCount: '6',
        webLink: 'https://f2e.sugarfun.com.tw/Brian/campaign/',
        webDesc: '迎財納福衝第一 (手機版網站)',
      },
      {
        CaseName: '限量典藏！<br>專屬感謝盒',
        CaseID: '100',
        CaseType: 'web',
        CoverImg: 'web_100.png',
        PhotoCount: '4',
        webLink: 'https://f2e.sugarfun.com.tw/Cathay/2025-fb-spotlight/index.html',
        webDesc: '國泰人壽【限量典藏！專屬感謝盒】',
      },
      {
        CaseName: 'iLeo 宇宙<br>能量探勘計畫',
        CaseID: '99',
        CaseType: 'web',
        CoverImg: 'web_99.png',
        PhotoCount: '4',
        webLink: 'https://f2e.sugarfun.com.tw/Brian/202406Event/',
        webDesc: 'iLeo 宇宙 能量探勘計畫 (手機版網站)',
      },
      {
        CaseName: '毛起來畫！<br>我畫你猜大挑戰',
        CaseID: '98',
        CaseType: 'web',
        CoverImg: 'web_98.png',
        PhotoCount: '5',
        webLink: 'https://f2e.sugarfun.com.tw/royalcanin/2024-q2crm/',
        webDesc: '毛起來畫！我畫你猜大挑戰',
      },
      {
        CaseName: '法國皇家<br>寵物年齡換算器',
        CaseID: '96',
        CaseType: 'web',
        CoverImg: 'web_96.png',
        PhotoCount: '5',
        webLink: 'https://royalcanin-petagecalculator-website.azurewebsites.net/',
        webDesc: '法國皇家｜寵物年齡換算器 (手機版網站)',
      },
      {
        CaseName: '數位生活圈<br>開幕嘉年華',
        CaseID: '97',
        CaseType: 'web',
        CoverImg: 'web_97.png',
        PhotoCount: '4',
        webLink: 'https://f2e.sugarfun.com.tw/Brian/2025brand/index.html',
        webDesc: '數位生活圈 開幕嘉年華',
      },
      {
        CaseName: '測出你的<br>共感類型',
        CaseID: '90',
        CaseType: 'web',
        CoverImg: 'web_90.png',
        PhotoCount: '3',
        webLink: 'https://www.msf.org.tw/campaign/whereithurtsquiz/',
        webDesc: '測出你的共感類型 | 無國界醫生',
      },
      {
        CaseName: '無國界醫生<br>痛，我願同行',
        CaseID: '89',
        CaseType: 'web',
        CoverImg: 'web_89.png',
        PhotoCount: '5',
        webLink: 'https://www.msf.org.tw/campaign/whereithurts/',
        webDesc: '痛，我願同行 人道醫療展 x 故事音樂節 | 無國界醫生',
      },
      {
        CaseName: 'KOKO<br>斷糧求生懶人包',
        CaseID: '54',
        CaseType: 'web',
        CoverImg: 'web_54.png',
        PhotoCount: '6',
        webLink: 'https://f2e.sugarfun.com.tw/Cathay/KoKo/5050/website/views/Home/index.html',
        webDesc: 'KOKO 斷糧求生懶人包',
      },
      {
        CaseName: '永豐行動銀行<br>全面改版',
        CaseID: '102',
        CaseType: 'web',
        CoverImg: 'web_102.png',
        PhotoCount: '3',
        webLink: 'https://f2e.sugarfun.com.tw/BSP_005/index.html',
        webDesc: '永豐行動銀行 全面改版',
      },
      {
        CaseName: '3M - 給我一個<br>賴床理由',
        CaseID: '43',
        CaseType: 'web',
        CoverImg: 'web_43.png',
        PhotoCount: '3',
        webLink: 'https://f2e.sugarfun.com.tw/3m/website/Views/Home/',
        webDesc: '3M 給我一個賴床理由',
      },
      {
        CaseName: '南山人壽<br>保障評估',
        CaseID: '111',
        CaseType: 'web',
        CoverImg: 'web_111.png',
        PhotoCount: '3',
        webLink:
          'https://f2e.sugarfun.com.tw/nsl/views/desktop/nslcp_pages/needanalysis/index.html',
        webDesc: '南山人壽保障評估',
      },
      {
        CaseName: 'Longchamp<br>搖搖馬樂園',
        CaseID: '110',
        CaseType: 'web',
        CoverImg: 'web_110.png',
        PhotoCount: '3',
        webLink: 'https://f2e.sugarfun.com.tw/longchamp/26cny-pop-up-event/',
        webDesc: 'Longchamp 搖搖馬樂園 (手機版網站)',
      },
      {
        CaseName: '台新私人銀行',
        CaseID: '114',
        CaseType: 'web',
        CoverImg: 'web_114.png',
        PhotoCount: '4',
        webLink: 'https://mkp.taishinbank.com.tw/s/2026/TS_PrivateBanking/index.html',
        webDesc: '台新私人銀行 (AI 協作作品)',
      },
      {
        CaseName: 'New Balance<br>灰境計劃',
        CaseID: '88',
        CaseType: 'web',
        CoverImg: 'web_88.png',
        PhotoCount: '5',
        webLink: 'https://f2e.sugarfun.com.tw/NB/grey/index.html',
        webDesc: 'THE GREY MISSIONS 灰境計劃 (手機版網站)',
      },
      {
        CaseName: '穿上 NB <br>從新出發',
        CaseID: '87',
        CaseType: 'web',
        CoverImg: 'web_87.png',
        PhotoCount: '4',
        webLink: 'https://f2e.sugarfun.com.tw/NB/CNY2023/index.html',
        webDesc: '穿上 NB 從新出發 (手機版網站)',
      },
      {
        CaseName: 'New Balance<br>1906 復刻潮！',
        CaseID: '86',
        CaseType: 'web',
        CoverImg: 'web_86.png',
        PhotoCount: '4',
        webLink: 'https://f2e.sugarfun.com.tw/NB/1906/index.html',
        webDesc: 'NB 1906 復刻潮！(手機版網站)',
      },
      {
        CaseName: '樂遊東京<br>有夠 High',
        CaseID: '91',
        CaseType: 'web',
        CoverImg: 'web_91.png',
        PhotoCount: '1',
        webLink: 'https://f2e.sugarfun.com.tw/Mega/2020Q1/index.html',
        webDesc: '兆豐銀行線上結匯 - 樂遊東京有夠 High 極速換匯超利 High',
      },
      {
        CaseName: 'Gucci<br>Garden',
        CaseID: '46',
        CaseType: 'web',
        CoverImg: 'web_46.png',
        PhotoCount: '5',
        webLink:
          'https://f2e.sugarfun.com.tw/Gucci/website/index.html,https://f2e.sugarfun.com.tw/Gucci/website/ticket.html,https://f2e.sugarfun.com.tw/Gucci/website/shop.html,https://f2e.sugarfun.com.tw/Gucci/gallery/gallery.html,https://f2e.sugarfun.com.tw/Gucci/gallery/gallery-details.html?id=5',
        webDesc: '首頁,票券頁,專門店資訊,展覽資訊,活動介紹',
      },
      {
        CaseName: '消一波！<br>奴曆七月業障重',
        CaseID: '82',
        CaseType: 'web',
        CoverImg: 'web_82.png',
        PhotoCount: '3',
        webLink: 'https://f2e.sugarfun.com.tw/Sugarfun/Event/karma/Views/Home/index.html',
        webDesc: '消一波！奴曆七月業障重 (手機版網站)',
      },
      {
        CaseName: '社畜自救指南',
        CaseID: '81',
        CaseType: 'web',
        CoverImg: 'web_81.png',
        PhotoCount: '4',
        webLink: 'https://f2e.sugarfun.com.tw/Sugarfun/Event/wageslave/Views/Home/index.html',
        webDesc: '社畜自救指南 (手機版網站)',
      },
      {
        CaseName: 'OLAY',
        CaseID: '85',
        CaseType: 'web',
        CoverImg: 'web_85.png',
        PhotoCount: '4',
        webLink: 'https://f2e.sugarfun.com.tw/Olay/website/index.html',
        webDesc: 'OLAY 高效透白光塑淡斑精華',
      },
      {
        CaseName: 'ScalpX',
        CaseID: '84',
        CaseType: 'web',
        CoverImg: 'web_84.png',
        PhotoCount: '3',
        webLink: 'https://f2e.sugarfun.com.tw/PG/index.html',
        webDesc: 'ScalpX 頭皮科研養髮三部曲',
      },
      {
        CaseName: '新光人壽<br>男女眉角大不同',
        CaseID: '83',
        CaseType: 'web',
        CoverImg: 'web_83.png',
        PhotoCount: '4',
        webLink: 'https://f2e.sugarfun.com.tw/skl/hisandher/html/Views/Home/index.html',
        webDesc: '新光人壽 男女眉角大不同',
      },
      {
        CaseName: '尾牙加碼製造機',
        CaseID: '107',
        CaseType: 'web',
        CoverImg: 'web_107.png',
        PhotoCount: '3',
        webLink: 'https://f2e.sugarfun.com.tw/Feds/catchfall/index.html',
        webDesc: '尾牙加碼製造機 (手機版網站)',
      },
      {
        CaseName: '你的老派<br>好不浪漫',
        CaseID: '105',
        CaseType: 'web',
        CoverImg: 'web_105.png',
        PhotoCount: '4',
        webLink: 'https://f2e.sugarfun.com.tw/Feds/A13campaign/index.html',
        webDesc: '你的老派 好不浪漫',
      },
      {
        CaseName: '團援！一起幫助<br>野孩子回家',
        CaseID: '75',
        CaseType: 'web',
        CoverImg: 'web_75.png',
        PhotoCount: '4',
        webLink: 'https://f2e.sugarfun.com.tw/Taishin/Richart/friend/event6/index.html',
        webDesc: '【Richart 台新Ｘ野灣 】 團援！一起幫助野孩子回家',
      },
      {
        CaseName: 'Richart<br>微笑連署書',
        CaseID: '74',
        CaseType: 'web',
        CoverImg: 'web_74.png',
        PhotoCount: '1',
        webLink: 'https://f2e.sugarfun.com.tw/Taishin/Richart/friend/event3/Views/Home/index.html',
        webDesc: '微笑連署書 一起不流浪 -Richart x 浪浪別哭- (手機版網站)',
      },
      {
        CaseName: '毛孩告急！<br>救援浪浪',
        CaseID: '73',
        CaseType: 'web',
        CoverImg: 'web_73.png',
        PhotoCount: '1',
        webLink: 'https://f2e.sugarfun.com.tw/Taishin/Richart/friend/event2/Views/Home/index.html',
        webDesc: '毛孩告急！救援浪浪 不再忽視',
      },
      {
        CaseName: 'Richart 和<br>你一起助養浪浪',
        CaseID: '72',
        CaseType: 'web',
        CoverImg: 'web_72.png',
        PhotoCount: '1',
        webLink: 'https://f2e.sugarfun.com.tw/Taishin/Richart/friend/event1/Views/Home/index.html',
        webDesc: 'Richart 和你一起助養浪浪',
      },
      {
        CaseName: '兆豐商銀<br>錢錢溝通室',
        CaseID: '92',
        CaseType: 'web',
        CoverImg: 'web_92.png',
        PhotoCount: '4',
        webLink: 'https://f2e.sugarfun.com.tw/Mega/2023chatroom/index.html',
        webDesc: '錢錢溝通室 - 兆豐機器人理財 e 把兆 (手機版網站)',
      },
      {
        CaseName: 'Cartier<br>愛的關鍵字',
        CaseID: '60',
        CaseType: 'web',
        CoverImg: 'web_60.png',
        PhotoCount: '3',
        webLink: 'https://f2e.sugarfun.com.tw/Cartier/VDay/',
        webDesc: 'Cartier 愛的關鍵字',
      },
      {
        CaseName: 'Cartier<br>2024 新春活動',
        CaseID: '59',
        CaseType: 'web',
        CoverImg: 'web_59.png',
        PhotoCount: '3',
        webLink: 'https://f2e.sugarfun.com.tw/Cartier/CNY2024/?',
        webDesc: '選擇新年祝賀，點亮珍貴心意 | Cartier (手機版網站)',
      },
      {
        CaseName: 'Cartier<br>2023 新春活動',
        CaseID: '58',
        CaseType: 'web',
        CoverImg: 'web_58.png',
        PhotoCount: '1',
        webLink: 'https://f2e.sugarfun.com.tw/Cartier/CNY2023/index.html',
        webDesc: '來自卡地亞的新春祝福 (手機版網站)',
      },
      {
        CaseName: 'Cartier<br>2022 新春活動',
        CaseID: '57',
        CaseType: 'web',
        CoverImg: 'web_57.png',
        PhotoCount: '3',
        webLink: 'https://f2e.sugarfun.com.tw/Cartier/CNY/index.html',
        webDesc: '來自卡地亞的新春祝福',
      },
      {
        CaseName: 'Chloé<br>新春專屬桌布',
        CaseID: '52',
        CaseType: 'web',
        CoverImg: 'web_52.png',
        PhotoCount: '4',
        webLink: 'https://f2e.sugarfun.com.tw/Chloe/index.html',
        webDesc: 'Chloé 新春專屬桌布 (手機版網站)',
      },
      {
        CaseName: 'KOKO<br>都市傳說',
        CaseID: '55',
        CaseType: 'web',
        CoverImg: 'web_55.png',
        PhotoCount: '2',
        webLink: 'https://f2e.sugarfun.com.tw/Cathay/KoKo/Combo/webiste/index.html',
        webDesc: 'KOKO COMBO 卡 － 5% 都市傳說',
      },
      {
        CaseName: '活存 V.S 定存<br>大解密',
        CaseID: '80',
        CaseType: 'web',
        CoverImg: 'web_80.png',
        PhotoCount: '3',
        webLink: 'https://f2e.sugarfun.com.tw/Taishin/Richart/rate/Views/Home/index.html',
        webDesc: '活存 V.S 定存大解密',
      },
      {
        CaseName: 'Richart<br>練金人生大富翁',
        CaseID: '79',
        CaseType: 'web',
        CoverImg: 'web_79.png',
        PhotoCount: '4',
        webLink: 'https://f2e.sugarfun.com.tw/Taishin/Richart/rich/Views/Home/index.html',
        webDesc: '練金人生大富翁',
      },
      {
        CaseName: 'Richart<br>好友出任務',
        CaseID: '78',
        CaseType: 'web',
        CoverImg: 'web_78.png',
        PhotoCount: '3',
        webLink: 'https://f2e.sugarfun.com.tw/Taishin/Richart/MGM/event2/Views/Home/index.html',
        webDesc: 'Richart 好友出任務',
      },
      {
        CaseName: 'Richart<br>友情大考驗',
        CaseID: '77',
        CaseType: 'web',
        CoverImg: 'web_77.png',
        PhotoCount: '2',
        webLink: 'https://f2e.sugarfun.com.tw/Taishin/Richart/MGM/event1/Views/Home/index.html',
        webDesc: 'Richart 限時闖關拿 10 萬',
      },
      {
        CaseName: 'Richart<br>練財神回應',
        CaseID: '76',
        CaseType: 'web',
        CoverImg: 'web_76.png',
        PhotoCount: '3',
        webLink: 'https://f2e.sugarfun.com.tw/Taishin/Richart/invest/Views/Home/index.html',
        webDesc: 'Richart 2017 練財神回應',
      },
      {
        CaseName: 'Richart x<br>friDay',
        CaseID: '71',
        CaseType: 'web',
        CoverImg: 'web_71.png',
        PhotoCount: '2',
        webLink: 'https://f2e.sugarfun.com.tw/Taishin/Richart/friday/Views/Home/index.html',
        webDesc: 'Richart x friDay 影音',
      },
      {
        CaseName: 'Richart<br>一歲慶生會',
        CaseID: '70',
        CaseType: 'web',
        CoverImg: 'web_70.png',
        PhotoCount: '2',
        webLink: 'https://f2e.sugarfun.com.tw/Taishin/Richart/birthday/Views/Home/index.html',
        webDesc: 'Richart 一歲慶生會',
      },
      {
        CaseName: '與你相遇<br>我很幸運',
        CaseID: '67',
        CaseType: 'web',
        CoverImg: 'web_67.png',
        PhotoCount: '3',
        webLink: 'https://f2e.sugarfun.com.tw/Taishin/Richart/2020/index.html',
        webDesc: '與你相遇，我很幸運',
      },
      {
        CaseName: 'RICHART<br>和你 17 賺翻天',
        CaseID: '69',
        CaseType: 'web',
        CoverImg: 'web_69.png',
        PhotoCount: '3',
        webLink: 'https://f2e.sugarfun.com.tw/Taishin/Richart/17life/Views/Home/index.html',
        webDesc: 'RICHART 和你 17 賺翻天',
      },
      {
        CaseName: '澎澎 MAN',
        CaseID: '103',
        CaseType: 'web',
        CoverImg: 'web_103.png',
        PhotoCount: '3',
        webLink: 'https://www.nice.com.tw/ponponman-face-wash/',
        webDesc: '澎澎 MAN 胺基酸洗面乳全系列',
      },
      {
        CaseName: '全球人壽<br>好奇星大冒險',
        CaseID: '64',
        CaseType: 'web',
        CoverImg: 'web_64.png',
        PhotoCount: '3',
        webLink: 'https://f2e.sugarfun.com.tw/Transglobe/opening2020/index.html',
        webDesc: '全球人壽 好奇星大冒險',
      },
      {
        CaseName: '我的美麗日記<br>美麗超能力',
        CaseID: '63',
        CaseType: 'web',
        CoverImg: 'web_63.png',
        PhotoCount: '1',
        webLink: 'https://f2e.sugarfun.com.tw/Beauty/actQ4/Index.html',
        webDesc: '我的美麗日記｜美麗超能力',
      },
      {
        CaseName: '我的美麗日記<br>春の戀愛淨白肌',
        CaseID: '62',
        CaseType: 'web',
        CoverImg: 'web_62.png',
        PhotoCount: '3',
        webLink: 'https://f2e.sugarfun.com.tw/Beauty/2019/Views/Home/Index.html',
        webDesc: '我的美麗日記｜春の戀愛淨白肌',
      },
      {
        CaseName: '跟著我的美麗<br>日記去旅行',
        CaseID: '61',
        CaseType: 'web',
        CoverImg: 'web_61.png',
        PhotoCount: '2',
        webLink: 'https://f2e.sugarfun.com.tw/Beauty/travel/Views/Home/Index.html',
        webDesc: '跟著我的美麗日記去旅行',
      },
      {
        CaseName: '國泰一日生活圈',
        CaseID: '53',
        CaseType: 'web',
        CoverImg: 'web_53.png',
        PhotoCount: '3',
        webLink: 'https://f2e.sugarfun.com.tw/Cathay/expo/index.html',
        webDesc: '國泰線上展【國泰一日生活圈】',
      },
      {
        CaseName: '永豐 DAWHO<br>大戶登大郎！',
        CaseID: '50',
        CaseType: 'web',
        CoverImg: 'web_50.png',
        PhotoCount: '1',
        webLink: 'https://f2e.sugarfun.com.tw/Dawho/dawho18/index.html',
        webDesc: '大戶登大郎！3% 優利、好禮等你拿｜永豐 DAWHO',
      },
      {
        CaseName: '地表最夯手機<br>由你決定！',
        CaseID: '51',
        CaseType: 'web',
        CoverImg: 'web_51.png',
        PhotoCount: '3',
        webLink: 'https://f2e.sugarfun.com.tw/FETnet/stars/views/Home/Index.html',
        webDesc: '遠傳送地表最夯手機',
      },
      {
        CaseName: 'Glenfiddich<br>格蘭菲迪',
        CaseID: '44',
        CaseType: 'web',
        CoverImg: 'web_44.png',
        PhotoCount: '2',
        webLink: 'https://f2e.sugarfun.com.tw/GlenFiddich/Views/Index.html',
        webDesc: 'Glenfiddich 格蘭菲迪',
      },
      {
        CaseName: '遠傳<br>資費得來速',
        CaseID: '49',
        CaseType: 'web',
        CoverImg: 'web_49.png',
        PhotoCount: '4',
        webLink: 'https://f2e.sugarfun.com.tw/FETnet/tariff/Index.html',
        webDesc: '遠傳 資費得來速',
      },
      {
        CaseName: '貓奴狗奴看過來',
        CaseID: '48',
        CaseType: 'web',
        CoverImg: 'web_48.png',
        PhotoCount: '3',
        webLink:
          'https://f2e.sugarfun.com.tw/FETnet/pets/views/Home/Index.html,https://f2e.sugarfun.com.tw/FETnet/pets/views/Home/dialog.html,https://f2e.sugarfun.com.tw/FETnet/pets/views/Home/Product-Housekeeper.html',
        webDesc: '首頁,互動頁,產品頁',
      },
      {
        CaseName: 'LINE MOBILE<br>歷屆活動',
        CaseID: '47',
        CaseType: 'web',
        CoverImg: 'web_47.png',
        PhotoCount: '3',
        webLink:
          'https://f2e.sugarfun.com.tw/FETnet/dna/website/Index-full.html,https://f2e.sugarfun.com.tw/FETnet/line-mobile/2020/Views/index.html,https://f2e.sugarfun.com.tw/FETnet/line-mobile/2019/Views/index.html',
        webDesc: 'LINE MOBILE 重磅好康 立即搶購,LINE MOBILE 驚喜島,LINE MOBILE 驚喜大飯店',
      },
      {
        CaseName: '喘口氣，<br>記得照顧自己',
        CaseID: '109',
        CaseType: 'web',
        CoverImg: 'web_109.png',
        PhotoCount: '2',
        webLink: 'https://f2e.sugarfun.com.tw/DrP/Q3/index.html',
        webDesc: '喘口氣，記得照顧自己',
      },
      {
        CaseName: '翡翠會員計劃',
        CaseID: '66',
        CaseType: 'web',
        CoverImg: 'web_66.png',
        PhotoCount: '1',
        webLink: 'https://f2e.sugarfun.com.tw/Taishin/Asset/website/Views/Home/index.html',
        webDesc: '台新銀行 翡翠會員計劃',
      },
      {
        CaseName: '瑞銀私人<br>財富俱樂部',
        CaseID: '65',
        CaseType: 'web',
        CoverImg: 'web_65.png',
        PhotoCount: '3',
        webLink: 'https://f2e.sugarfun.com.tw/UBS/website/Views/Home/index.html',
        webDesc: '瑞銀私人財富俱樂部',
      },
      {
        CaseName: '法國巴黎產險',
        CaseID: '106',
        CaseType: 'web',
        CoverImg: 'web_106.png',
        PhotoCount: '1',
        webLink: 'https://f2e.sugarfun.com.tw/BNP-life/onboarding/insurance/index.html',
        webDesc: '法國巴黎產險',
      },
      {
        CaseName: '基力加<br>全能機能飲',
        CaseID: '104',
        CaseType: 'web',
        CoverImg: 'web_104.png',
        PhotoCount: '3',
        webLink: 'https://www.nutrifuel-sarcojoint.com.tw/',
        webDesc: '基力加全能機能飲',
      },
      {
        CaseName: '全家鮮食平台',
        CaseID: '27',
        CaseType: 'web',
        CoverImg: 'web_27.png',
        PhotoCount: '4',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '永慶房屋<br>房仲科技 3.0',
        CaseID: '31',
        CaseType: 'web',
        CoverImg: 'web_31.png',
        PhotoCount: '3',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '中國信託<br>活動網頁',
        CaseID: '24',
        CaseType: 'web',
        CoverImg: 'web_24.png',
        PhotoCount: '2',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '家在雙和<br>活力 UP UP!',
        CaseID: '42',
        CaseType: 'web',
        CoverImg: 'web_42.png',
        PhotoCount: '1',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '好房網<br>新屋博覽會',
        CaseID: '32',
        CaseType: 'web',
        CoverImg: 'web_32.png',
        PhotoCount: '2',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '好房網新聞活動',
        CaseID: '30',
        CaseType: 'web',
        CoverImg: 'web_30.png',
        PhotoCount: '3',
        webLink: 'http://event.housefun.com.tw/329mag_press_conference/,,',
        webDesc: '好房網不動產市場週報 創刊發表暨記者會,,',
      },
    ],
  },
  {
    type: '專案作品',
    case: [
      {
        CaseName: '台新新光金控',
        CaseID: '56',
        CaseType: 'web',
        CoverImg: 'web_56.png',
        PhotoCount: '6',
        webLink: 'https://www.tsholdings.com.tw/tsh/',
        webDesc: '台新新光金控',
      },
      {
        CaseName: 'SUGARFUN<br>CREATIVE',
        CaseID: '101',
        CaseType: 'web',
        CoverImg: 'web_101.png',
        PhotoCount: '4',
        webLink: 'https://www.sugarfun.com.tw/',
        webDesc: 'SUGARFUN CREATIVE 方形糖創意數位',
      },
      {
        CaseName: '達爾生技',
        CaseID: '95',
        CaseType: 'web',
        CoverImg: 'web_95.png',
        PhotoCount: '5',
        webLink: 'https://www.delbioww.com/tw/Home/Index',
        webDesc: '達爾生技',
      },
      {
        CaseName: '遠東百貨<br>餐廳訂候位系統',
        CaseID: '108',
        CaseType: 'web',
        CoverImg: 'web_108.png',
        PhotoCount: '4',
        webLink: 'https://f2e.sugarfun.com.tw/Feds/booking/Views/Home/index.html',
        webDesc: '遠東百貨餐廳訂候位系統',
      },
      {
        CaseName: '漢來美食',
        CaseID: '45',
        CaseType: 'web',
        CoverImg: 'web_45.png',
        PhotoCount: '5',
        webLink: 'https://f2e.sugarfun.com.tw/Hanlai/Food/2016/website/index.html',
        webDesc: '漢來美食',
      },
      {
        CaseName: 'illuma 啟賦 3',
        CaseID: '112',
        CaseType: 'web',
        CoverImg: 'web_112.png',
        PhotoCount: '5',
        webLink: 'https://f2e.sugarfun.com.tw/illuma/Official/2018/Views/Home/',
        webDesc: '惠氏 illuma 啟賦 3',
      },
      {
        CaseName: '遠東百貨',
        CaseID: '93',
        CaseType: 'web',
        CoverImg: 'web_93.png',
        PhotoCount: '3',
        webLink: 'https://www.feds.com.tw/',
        webDesc: '遠東百貨',
      },
      {
        CaseName: '台新投信',
        CaseID: '68',
        CaseType: 'web',
        CoverImg: 'web_68.png',
        PhotoCount: '4',
        webLink: 'https://f2e.sugarfun.com.tw/Taishin/SIT/Views/home/index.html',
        webDesc: '台新投信',
      },
      {
        CaseName: '好房網',
        CaseID: '33',
        CaseType: 'web',
        CoverImg: 'web_33.png',
        PhotoCount: '4',
        webLink: 'http://www.housefun.com.tw/',
        webDesc: '好房網',
      },
      {
        CaseName: '好房網 M 版',
        CaseID: '38',
        CaseType: 'web',
        CoverImg: 'web_38.png',
        PhotoCount: '1',
        webLink: 'http://buy.housefun.com.tw/mobile',
        webDesc: '好房網 M 版',
      },
      {
        CaseName: '好房網市場週報',
        CaseID: '29',
        CaseType: 'web',
        CoverImg: 'web_29.png',
        PhotoCount: '4',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '遠傳電信',
        CaseID: '37',
        CaseType: 'web',
        CoverImg: 'web_37.png',
        PhotoCount: '4',
        webLink: 'https://www.fetnet.net/content/cbu/tw/index.html',
        webDesc: '遠傳電信',
      },
      {
        CaseName: '華南財富管理',
        CaseID: '39',
        CaseType: 'web',
        CoverImg: 'web_39.png',
        PhotoCount: '4',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '中租租車',
        CaseID: '26',
        CaseType: 'web',
        CoverImg: 'web_26.png',
        PhotoCount: '3',
        webLink: 'https://www.rentalcar.com.tw/',
        webDesc: '中租租車官方網站',
      },
      {
        CaseName: '中國信託<br>保險經紀人',
        CaseID: '23',
        CaseType: 'web',
        CoverImg: 'web_23.png',
        PhotoCount: '3',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '澳盛銀行',
        CaseID: '40',
        CaseType: 'web',
        CoverImg: 'web_40.png',
        PhotoCount: '3',
        webLink: 'https://www.anz.com/institutional/global/taiwan/zh-hant/',
        webDesc: '澳盛銀行 - 遙控理財',
      },
      {
        CaseName: '中國信託<br>商業銀行',
        CaseID: '36',
        CaseType: 'web',
        CoverImg: 'web_36.png',
        PhotoCount: '4',
        webLink: 'https://www.ctbcbank.com/twrbo/zh_tw/index.html',
        webDesc: '中國信託商業銀行',
      },
      {
        CaseName: '正宇生技',
        CaseID: '34',
        CaseType: 'web',
        CoverImg: 'web_34.png',
        PhotoCount: '3',
        webLink: 'http://zybio.com.tw/',
        webDesc: '正宇生技',
      },
      {
        CaseName: '好房網雙訊',
        CaseID: '10',
        CaseType: 'other',
        CoverImg: 'other_10.png',
        PhotoCount: '2',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: 'LUXGEN',
        CaseID: '41',
        CaseType: 'web',
        CoverImg: 'web_41.png',
        PhotoCount: '5',
        webLink: 'https://www.luxgen-motor.com.tw/',
        webDesc: 'LUXGEN 納智捷汽車',
      },
      {
        CaseName: '中國信託 CI',
        CaseID: '25',
        CaseType: 'web',
        CoverImg: 'web_25.png',
        PhotoCount: '3',
        webLink: '',
        webDesc: '',
      },
    ],
  },
  {
    type: '其他作品',
    case: [
      {
        CaseName: 'Wine95 Blog',
        CaseID: '16',
        CaseType: 'web',
        CoverImg: 'web_16.png',
        PhotoCount: '2',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: 'airiti Nature',
        CaseID: '15',
        CaseType: 'web',
        CoverImg: 'web_15.png',
        PhotoCount: '4',
        webLink: 'http://www.airitinature.com',
        webDesc: '華藝自然世界',
      },
      {
        CaseName: 'design ptc',
        CaseID: '13',
        CaseType: 'web',
        CoverImg: 'web_13.png',
        PhotoCount: '3',
        webLink: 'http://www.designptc.com/',
        webDesc: 'Patterns Textiles & Concepts',
      },
      {
        CaseName: 'Wine95',
        CaseID: '14',
        CaseType: 'web',
        CoverImg: 'web_14.png',
        PhotoCount: '3',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '喬杰設技工程',
        CaseID: '12',
        CaseType: 'web',
        CoverImg: 'web_12.png',
        PhotoCount: '4',
        webLink: 'http://www.spid.com.tw',
        webDesc: '喬杰設技工程',
      },
      {
        CaseName: '立象科技',
        CaseID: '09',
        CaseType: 'web',
        CoverImg: 'web_09.png',
        PhotoCount: '2',
        webLink: 'http://www.argox.com/',
        webDesc: '立象科技',
      },
      {
        CaseName: '桃園假日飯店',
        CaseID: '04',
        CaseType: 'web',
        CoverImg: 'web_04.png',
        PhotoCount: '2',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '賽先生<br>科學玩具購物網',
        CaseID: '10',
        CaseType: 'web',
        CoverImg: 'web_10.png',
        PhotoCount: '3',
        webLink: 'https://www.mr-sai.com/',
        webDesc: '賽先生科學玩具購物網',
      },
      {
        CaseName: '設計師交流之夜',
        CaseID: '20',
        CaseType: 'web',
        CoverImg: 'web_20.png',
        PhotoCount: '3',
        webLink: 'https://www.xuexue.tw/pkn/',
        webDesc: 'PKN 設計師交流之夜',
      },
      {
        CaseName: '布瓦布榭<br>設計工作坊',
        CaseID: '28',
        CaseType: 'web',
        CoverImg: 'web_28.png',
        PhotoCount: '3',
        webLink: 'http://www.xuexuefoundation.org.tw/boisbuchet/',
        webDesc: '布瓦布榭暑期設計工作坊',
      },
      {
        CaseName: '長新科技',
        CaseID: '11',
        CaseType: 'web',
        CoverImg: 'web_11.png',
        PhotoCount: '6',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '一口一口學<br>食驗室',
        CaseID: '22',
        CaseType: 'web',
        CoverImg: 'web_22.png',
        PhotoCount: '3',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: 'iRead<br>網路書店',
        CaseID: '17',
        CaseType: 'web',
        CoverImg: 'web_17.png',
        PhotoCount: '2',
        webLink: 'https://www.iread.com.tw/',
        webDesc: 'iRead灰熊愛讀書',
      },
      {
        CaseName: '1+1 來玩',
        CaseID: '21',
        CaseType: 'web',
        CoverImg: 'web_21.png',
        PhotoCount: '1',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '陽光瓦舍',
        CaseID: '01',
        CaseType: 'web',
        CoverImg: 'web_01.png',
        PhotoCount: '5',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: 'GALAXY',
        CaseID: '03',
        CaseType: 'web',
        CoverImg: 'web_03.png',
        PhotoCount: '4',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '商鐵咖啡',
        CaseID: '05',
        CaseType: 'web',
        CoverImg: 'web_05.png',
        PhotoCount: '2',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '昱廚',
        CaseID: '08',
        CaseType: 'web',
        CoverImg: 'web_08.png',
        PhotoCount: '3',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '星禾玫瑰園',
        CaseID: '06',
        CaseType: 'web',
        CoverImg: 'web_06.png',
        PhotoCount: '3',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '星禾出版社',
        CaseID: '07',
        CaseType: 'web',
        CoverImg: 'web_07.png',
        PhotoCount: '1',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: 'airiti Library',
        CaseID: '18',
        CaseType: 'web',
        CoverImg: 'web_18.png',
        PhotoCount: '3',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: 'airiti Books<br>活動網頁',
        CaseID: '19',
        CaseType: 'web',
        CoverImg: 'web_19.png',
        PhotoCount: '5',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '企業形象年報',
        CaseID: '02',
        CaseType: 'ad',
        CoverImg: 'ad_02.png',
        PhotoCount: '3',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '企業贈品',
        CaseID: '12',
        CaseType: 'ad',
        CoverImg: 'ad_12.png',
        PhotoCount: '1',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '各式 DM',
        CaseID: '13',
        CaseType: 'ad',
        CoverImg: 'ad_13.png',
        PhotoCount: '4',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '賀卡',
        CaseID: '11',
        CaseType: 'ad',
        CoverImg: 'ad_11.png',
        PhotoCount: '3',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '各式名片',
        CaseID: '05',
        CaseType: 'ad',
        CoverImg: 'ad_05.png',
        PhotoCount: '3',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '活動海報',
        CaseID: '14',
        CaseType: 'ad',
        CoverImg: 'ad_14.png',
        PhotoCount: '2',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '各式活動 EDM',
        CaseID: '01',
        CaseType: 'ad',
        CoverImg: 'ad_01.png',
        PhotoCount: '4',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: 'CI 規劃',
        CaseID: '03',
        CaseType: 'ad',
        CoverImg: 'ad_03.png',
        PhotoCount: '4',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '餐廳 MENU',
        CaseID: '10',
        CaseType: 'ad',
        CoverImg: 'ad_10.png',
        PhotoCount: '4',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: 'app實作 -<br>好房網雙訊',
        CaseID: '10',
        CaseType: 'other',
        CoverImg: 'other_10.png',
        PhotoCount: '2',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: 'app實作 -<br>iRead ebook',
        CaseID: '03',
        CaseType: 'other',
        CoverImg: 'other_03.png',
        PhotoCount: '3',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: 'app 提案 -<br>國寶菁華',
        CaseID: '04',
        CaseType: 'other',
        CoverImg: 'other_04.png',
        PhotoCount: '4',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: 'app 提案 -<br>世界美術',
        CaseID: '05',
        CaseType: 'other',
        CoverImg: 'other_05.png',
        PhotoCount: '2',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '空間設計 -<br>當地球停止轉動',
        CaseID: '09',
        CaseType: 'other',
        CoverImg: 'other_09.png',
        PhotoCount: '3',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '空間提案 -<br>墨水心',
        CaseID: '07',
        CaseType: 'other',
        CoverImg: 'other_07.png',
        PhotoCount: '1',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '空間提案 -<br>閃靈俠',
        CaseID: '08',
        CaseType: 'other',
        CoverImg: 'other_08.png',
        PhotoCount: '1',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '空間提案 -<br>赤壁二',
        CaseID: '06',
        CaseType: 'other',
        CoverImg: 'other_06.png',
        PhotoCount: '2',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '3D 建模 -<br>樓梯間',
        CaseID: '01',
        CaseType: 'other',
        CoverImg: 'other_01.png',
        PhotoCount: '3',
        webLink: '',
        webDesc: '',
      },
      {
        CaseName: '3D 建模 - 臥房',
        CaseID: '02',
        CaseType: 'other',
        CoverImg: 'other_02.png',
        PhotoCount: '3',
        webLink: '',
        webDesc: '',
      },
    ],
  },
]
